# Generated by Django 2.1.7 on 2019-03-18 09:03

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190318_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=main.models.get_image_path),
        ),
    ]
